-- =============================================================================
-- MCA Placement DB Schema
-- Safe to re-run: uses IF NOT EXISTS / DO blocks for idempotency
-- Run with: npm run db
-- =============================================================================

-- ── Core tables ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "users" (
  "id"                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"              varchar,
  "college_email_id"  varchar UNIQUE,
  "personal_email_id" varchar UNIQUE,
  "phone_number"      varchar,
  "aadhar"            VARCHAR,
  "linkedIn"          varchar,
  "gitHub"            varchar,
  "usn"               varchar,
  "google_id"         varchar,
  "ug_cgpa"           float,
  "first_sem_sgpa"    float,
  "tenth_marks"       float,
  "twelfth_marks"     float,
  "resume_url"        text,
  "verified"          boolean,
  "unlock_requested"  boolean DEFAULT false,
  "created_at"        timestamp
);

CREATE TABLE IF NOT EXISTS "spc_accounts" (
  "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"      int,
  "spc_username" varchar UNIQUE,
  "password"     varchar
);

CREATE TABLE IF NOT EXISTS "companies" (
  "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"           varchar,
  "min_cgpa"       float,
  "stipend"        varchar,
  "package"        varchar,
  "test_date"      date,
  "interview_date" date,
  "deadline"       timestamp,
  "created_by"     int,
  "status"         varchar DEFAULT 'ongoing',
  "created_at"     timestamp
);

CREATE TABLE IF NOT EXISTS "applications" (
  "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "company_id" int,
  "consent"    boolean,
  "tracker"    boolean
);

CREATE TABLE IF NOT EXISTS "forms" (
  "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title"      varchar,
  "type"       varchar,
  "company_id" int,
  "created_by" int,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "form_questions" (
  "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" varchar,
  "field_type"    varchar
);

CREATE TABLE IF NOT EXISTS "form_question_map" (
  "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id"     int,
  "question_id" int,
  "is_required" boolean
);

CREATE TABLE IF NOT EXISTS "form_responses" (
  "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id"     int,
  "student_id"  int,
  "company_id"  int,
  "question_id" int,
  "answer"      text
);

CREATE TABLE IF NOT EXISTS "messages" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id"       int NOT NULL,
  "message_text"    text,
  "attachment_url"  text,
  "attachment_name" text,
  "created_at"      timestamp DEFAULT NOW(),
  "updated_at"      timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "mentions" (
  "id"                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id"        int NOT NULL,
  "mentioned_user_id" int NOT NULL,
  CONSTRAINT "uq_mention" UNIQUE ("message_id", "mentioned_user_id")
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS "idx_messages_created_at"  ON "messages" ("created_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_mentions_message_id"  ON "mentions" ("message_id");

-- ── Foreign keys (each wrapped in a DO block so re-running is safe) ───────────

DO $$ BEGIN
  ALTER TABLE "spc_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "companies" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "applications" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "applications" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "forms" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "forms" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "form_question_map" ADD FOREIGN KEY ("form_id") REFERENCES "forms" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "form_question_map" ADD FOREIGN KEY ("question_id") REFERENCES "form_questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "form_responses" ADD FOREIGN KEY ("form_id") REFERENCES "forms" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "form_responses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "form_responses" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "form_responses" ADD FOREIGN KEY ("question_id") REFERENCES "form_questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "mentions" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "mentions" ADD FOREIGN KEY ("mentioned_user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "users" ADD COLUMN "unlock_requested" boolean DEFAULT false;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "companies" ADD COLUMN "status" varchar DEFAULT 'ongoing';
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "companies" ADD COLUMN "deadline" timestamp;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "messages" ADD COLUMN "attachment_url" text;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "messages" ADD COLUMN "attachment_name" text;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "messages" ALTER COLUMN "message_text" DROP NOT NULL;
EXCEPTION WHEN OTHERS THEN NULL; END $$;
